import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from '@/redux/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next Js Demo',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={"w-full max-w-5xl mx-auto  " +inter.className}>
      <h1 className="text-3xl font-bold text-center my-3 text-lime-900">Admin Panel</h1>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
